"""
LLM Clinical & Research Interpretation Service
=============================================
Uses the Gemini API to generate structured clinical impressions,
pathophysiological insights, and research-grade diagnostic explanations.
"""

from __future__ import annotations
import os
import json
import urllib.request
import urllib.error
from pathlib import Path
from typing import Dict, Any, Optional

PROJECT_ROOT = Path(__file__).resolve().parent.parent

FALLBACK_MODELS = [
    "gemini-2.5-flash",
    "gemini-1.5-flash",
    "gemini-1.5-pro",
    "gemini-pro"
]


def load_api_key() -> str:
    """Loads Gemini API key from environment variable or .env file."""
    key = os.environ.get("GEMINI_API_KEY", "")
    if not key:
        env_file = PROJECT_ROOT / ".env"
        if env_file.exists():
            for line in env_file.read_text().splitlines():
                if line.startswith("GEMINI_API_KEY="):
                    key = line.split("=", 1)[1].strip()
                    break
    return key


class GeminiClinicalInterpreter:
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or load_api_key()

    def generate_clinical_report(
        self,
        record_id: str,
        detected_conditions: list[str],
        probabilities: Dict[str, float],
        thresholds: Dict[str, float],
        biomarkers: Dict[str, Any],
        patient_metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Generates a structured medical interpretation using the Gemini LLM.
        """
        patient_meta = patient_metadata or {"Age": "Unknown", "Sex": "Unknown"}
        
        prompt = f"""
You are an expert cardiologist and cardiac electrophysiology AI researcher reviewing a 12-lead ECG analysis generated by the ECG Multimodal Foundation Representation System.

PATIENT & RECORD METADATA:
- Record ID: {record_id}
- Patient Age: {patient_meta.get('Age', 'N/A')}
- Patient Sex: {patient_meta.get('Sex', 'N/A')}

MULTIMODAL FOUNDATION SYSTEM OUTPUT:
- Detected Cardiac Conditions: {', '.join(detected_conditions) if detected_conditions else 'Normal Variant'}
- Diagnostic Class Probabilities (Calibrated Optimal F1 Thresholds):
{chr(10).join([f"  * {c}: {p*100:.1f}% (Decision Threshold: {thresholds.get(c, 0.5)*100:.1f}%)" for c, p in probabilities.items()])}

EXTRACTED CLINICAL BIOMARKERS (KEY METRICS):
{chr(10).join([f"  * {k}: {v:.2f}" if isinstance(v, (int, float)) else f"  * {k}: {v}" for k, v in list(biomarkers.items())[:15]])}

LATENT MULTIMODAL REPRESENTATION:
- Temporal Embedding (1D ResNet-SE): 512-dim
- Morphology Embedding (2D Spectrogram ResNet): 512-dim
- Biomarker Embedding (Attention MLP): 32-dim
- Unified Joint Space (z_fused): 1056-dim

TASK:
Provide a clear, authoritative, and structured clinical and research report. Structure your response in Markdown with the following exact sections:

### 1. Executive Summary & Clinical Impression
Brief summary of the primary rhythm, detected diagnostic conditions, and clinical urgency.

### 2. Electrophysiological & Morphological Findings
Detailed analysis of the ECG waveform contours, interval durations (PR, QRS, QT/QTc), ST-T segment dynamics, and heart rate variability (HRV).

### 3. Pathophysiological Mechanism
Explanation of the underlying cardiac cellular/conduction mechanisms driving these findings.

### 4. Multimodal AI Representation Insights
Discuss why fusing 1D temporal wave dynamics (z_t ∈ ℝ⁵¹²), 2D time-frequency morphology (z_m ∈ ℝ⁵¹²), and 60 clinical biomarkers (z_b ∈ ℝ³²) into a 1056-D representation provides high diagnostic confidence for this record. Use clean Unicode formatting for math symbols (e.g. ℝ, ∈, ⁵¹², ³, ²) rather than raw unrendered LaTeX markers.

### 5. Recommended Clinical Next Steps
Actionable next steps (e.g., serial troponins, echocardiography, Holter monitoring, electrophysiology consult, urgent cardiology referral).

Be professional, medically rigorous, and easy for both clinicians and research peers to understand.
"""

        # Try calling Gemini models with fallback if API key is available
        if self.api_key:
            for model in FALLBACK_MODELS:
                url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={self.api_key}"
                headers = {"Content-Type": "application/json"}
                payload = {
                    "contents": [
                        {
                            "parts": [{"text": prompt}]
                        }
                    ],
                    "generationConfig": {
                        "temperature": 0.3,
                        "maxOutputTokens": 1500
                    }
                }
                
                try:
                    req = urllib.request.Request(
                        url,
                        data=json.dumps(payload).encode("utf-8"),
                        headers=headers,
                        method="POST"
                    )
                    with urllib.request.urlopen(req, timeout=15) as response:
                        res_body = json.loads(response.read().decode("utf-8"))
                        text = res_body["candidates"][0]["content"]["parts"][0]["text"]
                        return {
                            "status": "success",
                            "model": model,
                            "report_markdown": text
                        }
                except Exception:
                    continue

        # Fallback heuristic clinical synthesizer
        return {
            "status": "fallback",
            "model": "offline_clinical_heuristics",
            "report_markdown": self._generate_offline_heuristic_report(
                record_id, detected_conditions, probabilities, biomarkers, patient_meta
            )
        }

    def _generate_offline_heuristic_report(
        self,
        record_id: str,
        detected_conditions: list[str],
        probabilities: Dict[str, float],
        biomarkers: Dict[str, Any],
        patient_meta: Dict[str, Any]
    ) -> str:
        conditions_str = ", ".join(detected_conditions) if detected_conditions else "Normal Sinus Rhythm"
        hr = int(60000 / biomarkers.get("RR_Mean", 850)) if biomarkers.get("RR_Mean", 0) > 0 else 72
        qrs = biomarkers.get("QRS_Duration", 88.0)
        qtc = biomarkers.get("QTc_Bazett", 415.0)
        
        return f"""### 1. Executive Summary & Clinical Impression
**Record ID {record_id}** presents findings consistent with **{conditions_str}**. 
Estimated Heart Rate is ~{hr} bpm with a QRS duration of {qrs:.1f} ms and QTc interval of {qtc:.1f} ms.

### 2. Electrophysiological & Morphological Findings
- **Heart Rate & Rhythm**: Average RR interval {biomarkers.get('RR_Mean', 850):.1f} ms (~{hr} bpm).
- **Conduction Intervals**: PR interval ({biomarkers.get('PR_Interval', 150):.1f} ms), QRS duration ({qrs:.1f} ms).
- **Repolarization**: QTc Bazett ({qtc:.1f} ms) within expected physiological tolerances.
- **HRV Autonomic Tone**: SDNN = {biomarkers.get('SDNN', 35):.1f} ms, RMSSD = {biomarkers.get('RMSSD', 28):.1f} ms.

### 3. Pathophysiological Mechanism
The multimodal encoder detected patterns reflecting myocardial electrical activation. 
In the presence of **{conditions_str}**, localized repolarization or conduction delays modify the 12-lead vector loops and spectral energy density.

### 4. Multimodal AI Representation Insights
The unified 1056-D latent vector integrates:
1. **Temporal Dynamics (z<sub>t</sub> ∈ ℝ⁵¹²)**: High-resolution inter-beat recurrence.
2. **Morphology (z<sub>m</sub> ∈ ℝ⁵¹²)**: 2D time-frequency wave contours and spectral magnitude.
3. **Biomarkers (z<sub>b</sub> ∈ ℝ³²)**: Clinical cardiac intervals and autonomic HRV indices.

### 5. Recommended Clinical Next Steps
- Correlate with patient symptoms (chest discomfort, palpitations, dyspnea).
- Review serial 12-lead ECGs and consider baseline echocardiogram and serum cardiac biomarkers if symptomatic.
"""
